server:
  port: 9090
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create

jwt:
  secret:
